cask_args appdir: '/Applications'

tap 'homebrew/bundle'

#brew 'azure-cli'
#brew 'coreutils'
#brew 'docker'
#brew 'gatsby-cli'
#brew 'git'
#brew 'go'
#brew 'grc'
#brew 'jp2a'
#brew 'kubectx'
#brew 'libgit2'
#brew 'openssl'
#brew 'node'
#brew 'postgresql'
#brew 'python'
#brew 'reattach-to-user-namespace'
#brew 'ruby-build'
#brew 'rbenv'
#brew 'shpotify'
#brew 'spaceman-diff'
#brew 'speedtest-cli'
#brew 'unrar'
#brew 'watch'
#brew 'yarn'
#brew 'youtube-dl'

cask 'iterm2'
#cask 'spotify'
#cask 'transmission'
#cask 'visual-studio-code'
#cask 'vlc'
